name: RedeemingFallenAngels
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8632
title: 'Personal Portfolio, Photography and News of Dreadjim'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-26797810-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe0000'
    - '#182335'
    - '#999ca3'
    - '#d6d9c4'
    - '#8d1f26'
  brandStrength: 0.5834717496763915
  lightness: 0.375
  saturation: 0.6721861299593002
  rhythmicContrast: 0.75
purpose: []
